### ISSUE TITLE
Component should extend from Vuetify Autocomplete component

### ISSUE THREAD

**Issue by Kocal** [Kocal/vuetify-algolia-places#119]
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VAutocomplete/VAutocomplete.js

By doing this, we will never need to add new props and pass them manually to `<v-autocomplete>` component, so we will be able to remove this:
```js
disabled: {
  type: Boolean,
  default: false,
},
required: {
  type: Boolean,
  default: false,
},
requiredMessage: {
  type: String,
  default: 'You must select a place',
},
rules: {
  type: Array,
  default() {
    return [v => (v && v.value !== '') || this.requiredMessage];
  },
},
label: {
  type: String,
  default: '',
},
```

**Comment by Kocal** [comment]
It does not seems possible because of styles being imported aside JS.

Maybe use a directive directly on `<v-autocomplete>`? E.g.: `<v-autocomplete v-algolia-places="{ countries: ['fr', 'en'] }">`

**Comment by axlf** [comment]
That would be great. It would open up, to validate the v-autocomplete field, and show some error messages.

**Comment by Kocal** [comment]
Yep that would be awesome. :+1: 

I think I will go for the directive

**Comment by Kocal** [comment]
Or in fact, maybe we can keep the component and pass all props/events to Vuetify Autocomplete? Like this `<v-autocomplete v-bind="$props" v-on="$events">`?

With the directive, I can't update Vuetify Autocomplete like I want, some properties are read only (there is a warning in the docs and in the console)
