### ISSUE TITLE
Debounce input

### ISSUE THREAD

**Issue by rubengees** [Kocal/vuetify-algolia-places#184]
When typing quickly, many requests to the algolia api are sent. Introducing debouncing could reduce the number of calls, while still staying responsive.

This could be done with [lodash.debounce](https://www.npmjs.com/package/lodash.debounce). Here is also a related issue in [Vuetify](https://github.com/vuetifyjs/vuetify/issues/835).

![Bildschirmfoto von 2019-04-16 10-50-41](https://user-images.githubusercontent.com/8021265/56195580-8b69a300-6035-11e9-91d5-b51ae906f25b.png)

**Comment by Kocal** [comment]
Hum that's true, it would be nice to have a prop `debounce` that accepts a boolean or a number (in ms). :+1: 

By default I think it should be disabled.

Would you mind opening a PR? :)
