### ISSUE TITLE
Debounce DependencyNotFoundError

### ISSUE THREAD

**Issue by douglasg14b** [Kocal/vuetify-algolia-places#187]
When using the most recent version I get the following error:

Could not find dependency: 'debounce' relative to '/node_modules/vuetify-algolia-places/src/VuetifyAlgoliaPlaces.vue'

Looks like this needs to be added as a dependency?

https://codesandbox.io/s/n9q4vv8o20

**Comment by douglasg14b** [comment]
scratch that. Thought the vuetify template for codesandbox actually had vuetify as a dependency already....

**Comment by Kocal** [comment]
Ah, yes, `debounce` is actually a peer dependency.
I will update the README

**Comment by Kocal** [comment]
Fixed with 1.0.0-beta.3
