### ISSUE TITLE
[bug] Unexpected identifier

### ISSUE THREAD

**Issue by thibaultchazal** [Kocal/vuetify-algolia-places#280]
Hi

First, thanks for this plugins that seems very usefull !

I just have an issue using it. I have a project running on nuxt with vuetify 2.0.
I tried to installed vuetify-algolia-places with npm then yarn but I get the same issue at the end : 
````js
SyntaxError
Unexpected identifier
````

I tried on Runkit and find the same problem : https://npm.runkit.com/vuetify-algolia-places

Am I the only one to have this issue ?
Thanks in advance for your help

**Comment by thibaultchazal** [comment]
I found a cure to my issue.
I share for anyone else who would get stuck.

In fact, you have to add transpile build option since ```vuetify-algolia-places``` use ES6 module.

Your ```nuxt.config.js``` should be:

````js
export default {
  build: {
    transpile: ['vuetify-algolia-places']
  }
````

Meanwhile, I have an other issue with the default language function I will discuss in another thread.

**Comment by Kocal** [comment]
Ah yes, I prefer to let the user handle the building process, for having more control on it.

But maybe we can provide source and dist builds... do you have any recommendation for the dist build? :thinking:
