### ISSUE TITLE
Changes to support Vuetify v2

### ISSUE THREAD

**Issue by kamikazechaser** [Kocal/vuetify-algolia-places#300]
There have been some minor changes that may slightly break this library. There could be a separate branch to support v2. For example v2 now uses mdi for icons, among other changes.  I can try and open a pr for the change.

**Comment by Kocal** [comment]
Hi, and thanks for pointing out what breaks with Vuetify 2, 

I wanted to add support for Vuetify 2 but I didn't have time for it. A PR would be really appreciated! 😄 

Thanks

**Comment by cavatron** [comment]
just opened a PR for a v2 upgrade (#314 )
