### ISSUE TITLE
How to add the map visualization ?

### ISSUE THREAD

**Issue by cococococococo** [Kocal/vuetify-algolia-places#497]
Everything is in the title. 
Algolia allow to have a leaflet map to visualize the location, how to add this  ?

**Comment by Kocal** [comment]
> Algolia allow to have a leaflet map to visualize the location

You're wrong, they describe [how to display Places results on a Leaflet map](https://community.algolia.com/places/examples.html#displaying-on-a-map), it's not a Places feature that you can use like this for example:
```js
const placesAutocomplete = place({
  // ...
  container: document.querySelector('#input')
  containerMap: document.querySelector('#map') 
})
```

To display a map, you can use https://github.com/xkjyeah/vue-google-maps and use `v-model` value from `<vuetify-algolia-places>` component.
